# Generated by Django 4.2.27 on 2026-01-06 06:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Booking Reference')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone')),
                ('number_of_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('booked_date', models.DateField(verbose_name='Booked Date')),
                ('session_start', models.TimeField(help_text='What time the customer will arrive', verbose_name='Session Start Time')),
                ('session_end', models.TimeField(blank=True, help_text='Calculated based on package duration', null=True, verbose_name='Session End Time')),
                ('booking_fee_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Booking Fee Paid')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('package_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Amount')),
                ('payment_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='draft', max_length=20, verbose_name='Payment Status')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference')),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='When the session actually started', null=True, verbose_name='Actual Start Time')),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='When the session actually ended', null=True, verbose_name='Actual End Time')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('booking_channel', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone')], default='website', max_length=20, verbose_name='Booking Channel')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booked_date', 'session_start'],
            },
        ),
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('booking_fee_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('cancellation_hours', models.PositiveIntegerField(default=24)),
                ('reschedule_hours', models.PositiveIntegerField(default=24)),
                ('max_group_size', models.PositiveIntegerField(default=8)),
                ('booking_validity_days', models.PositiveIntegerField(default=28)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('extra_clay', 'Extra Clay'), ('clay_takeaway', 'Clay Takeaway'), ('commercial_shooting', 'Commercial Shooting'), ('private_event', 'Private Event Workshop'), ('catered_event', 'Catered Private Event')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiringCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_category', models.CharField(choices=[('xs', 'Extra Small (smaller than standard cup)'), ('s', 'Small (≤10cm diameter)'), ('m', 'Medium (≤12cm diameter, 3-10cm height)'), ('l', 'Large (12-16cm diameter)'), ('xl', 'Extra Large (16-19cm diameter)'), ('xxl', '2XL (19-22cm diameter)'), ('plate_small', 'Plate Small (≤17cm diameter)'), ('plate_medium', 'Plate Medium (17-24cm diameter, ≤3cm height)'), ('plate_large', 'Plate Large (24-30cm diameter)'), ('tall', 'Tall (>10cm height)'), ('custom', 'Custom Size')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hobbyist_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_diameter_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('max_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('package_type', models.CharField(choices=[('wheel_throwing', 'Wheel Throwing'), ('hand_building', 'Hand Building'), ('combo', 'Wheel + Hand Building Combo'), ('painting', 'Bisque Painting/Glazing'), ('hobbyist', 'Hobbyists Package'), ('colored_clay', 'Colored Clay Combo')], max_length=100, verbose_name='Package Type')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Package Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Package Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Price')),
                ('has_fixed_duration', models.BooleanField(default=False, verbose_name='Has Fixed Duration')),
                ('fixed_duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='For Packages with fixed duration (P1, P2)', max_digits=4, null=True, verbose_name='Fixed Duration (Hours)')),
                ('max_duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum duration allowed for unlimited packages in hours (e.g., 0.5 to 8.0 hours)', max_digits=4, null=True, verbose_name='Max Duration (Hours)')),
                ('requires_wheel', models.BooleanField(default=False, verbose_name='Requires Wheel')),
                ('clay_weight_kg', models.DecimalField(blank=True, decimal_places=1, default=1.0, help_text='Amount of clay provided with the package in kilograms', max_digits=5, null=True, verbose_name='Clay Weight (kg)')),
                ('max_participants', models.PositiveIntegerField(default=1, help_text='Maximum number of participants allowed for group packages', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Max Participants')),
                ('display_features', models.TextField(blank=True, help_text='Features to display for this package on the booking page', null=True, verbose_name='Display Features')),
                ('display_suggestion', models.TextField(blank=True, help_text='Suggestions to display for this package on the booking page', null=True, verbose_name='Display Suggestion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaintingGlazingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('option_type', models.CharField(choices=[('self_paint', 'Self Painting'), ('self_glaze', 'Self Glazing'), ('single_color', 'Single Color Application'), ('transparent_glaze', 'Transparent Glaze Application'), ('white_glaze', 'White Glaze Application'), ('premium_glaze', 'Premium Natural Glaze')], max_length=20)),
                ('description', models.TextField()),
                ('price_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_session', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('includes_paints', models.BooleanField(default=False)),
                ('includes_tutorial', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['option_type', 'price_per_item'],
            },
        ),
        migrations.CreateModel(
            name='StudioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_wheels', models.PositiveIntegerField(default=8, verbose_name='Total Wheels')),
                ('booking_fee_per_person', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Booking Fee per Person')),
                ('operating_time', models.TimeField(default='08:00:00', verbose_name='Operating Time Start')),
                ('closing_time', models.TimeField(default='18:00:00', verbose_name='Closing Time')),
                ('buffer_minutes_between_sessions', models.PositiveIntegerField(default=15, verbose_name='Buffer Minutes Between Sessions')),
                ('max_daily_sessions', models.PositiveIntegerField(default=20, verbose_name='Max Daily Sessions')),
                ('wheel_session_duration', models.PositiveIntegerField(default=60, verbose_name='Wheel Session Duration (Minutes)')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('maintenance_message', models.TextField(blank=True, null=True, verbose_name='Maintenance Message')),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_number', models.PositiveIntegerField(unique=True, verbose_name='Wheel Number')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wheel Name')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=20, verbose_name='Wheel Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Wheel',
                'verbose_name_plural': 'Wheels',
                'ordering': ['wheel_number'],
            },
        ),
        migrations.CreateModel(
            name='WheelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_start_time', models.TimeField(blank=True, null=True, verbose_name='Wheel Session Start Time')),
                ('wheel_end_time', models.TimeField(blank=True, null=True, verbose_name='Wheel Session End Time')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_bookings', to='bookings.booking', verbose_name='Booking')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.wheel', verbose_name='Wheel')),
            ],
            options={
                'verbose_name': 'Wheel Booking',
                'verbose_name_plural': 'Wheel Bookings',
                'ordering': ['wheel__wheel_number'],
                'unique_together': {('booking', 'wheel')},
            },
        ),
        migrations.CreateModel(
            name='PostSessionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('firing', 'Firing Service'), ('painting', 'Painting Service'), ('glazing', 'Glazing Service'), ('extra_clay', 'Extra Clay'), ('other', 'Other Service')], max_length=20)),
                ('piece_count', models.PositiveIntegerField(default=1)),
                ('piece_description', models.TextField(blank=True)),
                ('diameter_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('item_count', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_session_services', to='bookings.booking')),
                ('extra_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.extraservice')),
                ('firing_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.firingcharge')),
                ('painting_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.paintingglazingoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_wheels',
            field=models.ManyToManyField(blank=True, through='bookings.WheelBooking', to='bookings.wheel', verbose_name='Assigned Wheels'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.package', verbose_name='Package'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_date', 'session_start'], name='bookings_bo_booked__db5aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_phone'], name='bookings_bo_custome_3b69ff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='bookings_bo_payment_27706e_idx'),
        ),
    ]
