export * from '../actions/packageActions';
export * from '../actions/bookingActions';
export * from '../actions/studioActions';

// Action Types Constants
export const ACTION_TYPES = {
    // Package Actions
    FETCH_PACKAGES_REQUEST: 'FETCH_PACKAGES_REQUEST',
    FETCH_PACKAGES_SUCCESS: 'FETCH_PACKAGES_SUCCESS',
    FETCH_PACKAGES_FAILURE: 'FETCH_PACKAGES_FAILURE',
    
    FETCH_PACKAGE_DETAILS_REQUEST: 'FETCH_PACKAGE_DETAILS_REQUEST',
    FETCH_PACKAGE_DETAILS_SUCCESS: 'FETCH_PACKAGE_DETAILS_SUCCESS',
    FETCH_PACKAGE_DETAILS_FAILURE: 'FETCH_PACKAGE_DETAILS_FAILURE',
    
    CHECK_PACKAGE_AVAILABILITY_REQUEST: 'CHECK_PACKAGE_AVAILABILITY_REQUEST',
    CHECK_PACKAGE_AVAILABILITY_SUCCESS: 'CHECK_PACKAGE_AVAILABILITY_SUCCESS',
    CHECK_PACKAGE_AVAILABILITY_FAILURE: 'CHECK_PACKAGE_AVAILABILITY_FAILURE',
    
    CLEAR_AVAILABILITY_DATA: 'CLEAR_AVAILABILITY_DATA',
    SELECT_PACKAGE: 'SELECT_PACKAGE',
    UPDATE_PACKAGE_FILTERS: 'UPDATE_PACKAGE_FILTERS',
    
    // Booking Actions
    CREATE_BOOKING_REQUEST: 'CREATE_BOOKING_REQUEST',
    CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
    CREATE_BOOKING_FAILURE: 'CREATE_BOOKING_FAILURE',
    
    QUICK_BOOKING_REQUEST: 'QUICK_BOOKING_REQUEST',
    QUICK_BOOKING_SUCCESS: 'QUICK_BOOKING_SUCCESS',
    QUICK_BOOKING_FAILURE: 'QUICK_BOOKING_FAILURE',
    
    FETCH_BOOKING_REQUEST: 'FETCH_BOOKING_REQUEST',
    FETCH_BOOKING_SUCCESS: 'FETCH_BOOKING_SUCCESS',
    FETCH_BOOKING_FAILURE: 'FETCH_BOOKING_FAILURE',
    
    FETCH_BOOKING_HISTORY_REQUEST: 'FETCH_BOOKING_HISTORY_REQUEST',
    FETCH_BOOKING_HISTORY_SUCCESS: 'FETCH_BOOKING_HISTORY_SUCCESS',
    FETCH_BOOKING_HISTORY_FAILURE: 'FETCH_BOOKING_HISTORY_FAILURE',
    
    RESCHEDULE_BOOKING_REQUEST: 'RESCHEDULE_BOOKING_REQUEST',
    RESCHEDULE_BOOKING_SUCCESS: 'RESCHEDULE_BOOKING_SUCCESS',
    RESCHEDULE_BOOKING_FAILURE: 'RESCHEDULE_BOOKING_FAILURE',
    
    CANCEL_BOOKING_REQUEST: 'CANCEL_BOOKING_REQUEST',
    CANCEL_BOOKING_SUCCESS: 'CANCEL_BOOKING_SUCCESS',
    CANCEL_BOOKING_FAILURE: 'CANCEL_BOOKING_FAILURE',
    
    CHECK_AVAILABILITY_REQUEST: 'CHECK_AVAILABILITY_REQUEST',
    CHECK_AVAILABILITY_SUCCESS: 'CHECK_AVAILABILITY_SUCCESS',
    CHECK_AVAILABILITY_FAILURE: 'CHECK_AVAILABILITY_FAILURE',
    
    FETCH_UPCOMING_BOOKINGS_REQUEST: 'FETCH_UPCOMING_BOOKINGS_REQUEST',
    FETCH_UPCOMING_BOOKINGS_SUCCESS: 'FETCH_UPCOMING_BOOKINGS_SUCCESS',
    FETCH_UPCOMING_BOOKINGS_FAILURE: 'FETCH_UPCOMING_BOOKINGS_FAILURE',
    
    CLEAR_BOOKING_DATA: 'CLEAR_BOOKING_DATA',
    UPDATE_BOOKING_FORM: 'UPDATE_BOOKING_FORM',
    
    // Studio Actions
    FETCH_STUDIO_CONFIG_REQUEST: 'FETCH_STUDIO_CONFIG_REQUEST',
    FETCH_STUDIO_CONFIG_SUCCESS: 'FETCH_STUDIO_CONFIG_SUCCESS',
    FETCH_STUDIO_CONFIG_FAILURE: 'FETCH_STUDIO_CONFIG_FAILURE',
    
    FETCH_STUDIO_STATUS_REQUEST: 'FETCH_STUDIO_STATUS_REQUEST',
    FETCH_STUDIO_STATUS_SUCCESS: 'FETCH_STUDIO_STATUS_SUCCESS',
    FETCH_STUDIO_STATUS_FAILURE: 'FETCH_STUDIO_STATUS_FAILURE',
    
    FETCH_DAILY_SCHEDULE_REQUEST: 'FETCH_DAILY_SCHEDULE_REQUEST',
    FETCH_DAILY_SCHEDULE_SUCCESS: 'FETCH_DAILY_SCHEDULE_SUCCESS',
    FETCH_DAILY_SCHEDULE_FAILURE: 'FETCH_DAILY_SCHEDULE_FAILURE',
    
    FETCH_FIRING_CHARGES_REQUEST: 'FETCH_FIRING_CHARGES_REQUEST',
    FETCH_FIRING_CHARGES_SUCCESS: 'FETCH_FIRING_CHARGES_SUCCESS',
    FETCH_FIRING_CHARGES_FAILURE: 'FETCH_FIRING_CHARGES_FAILURE',
    
    FETCH_PAINTING_OPTIONS_REQUEST: 'FETCH_PAINTING_OPTIONS_REQUEST',
    FETCH_PAINTING_OPTIONS_SUCCESS: 'FETCH_PAINTING_OPTIONS_SUCCESS',
    FETCH_PAINTING_OPTIONS_FAILURE: 'FETCH_PAINTING_OPTIONS_FAILURE',
    
    FETCH_EXTRA_SERVICES_REQUEST: 'FETCH_EXTRA_SERVICES_REQUEST',
    FETCH_EXTRA_SERVICES_SUCCESS: 'FETCH_EXTRA_SERVICES_SUCCESS',
    FETCH_EXTRA_SERVICES_FAILURE: 'FETCH_EXTRA_SERVICES_FAILURE',
    
    FETCH_BOOKING_RULES_REQUEST: 'FETCH_BOOKING_RULES_REQUEST',
    FETCH_BOOKING_RULES_SUCCESS: 'FETCH_BOOKING_RULES_SUCCESS',
    FETCH_BOOKING_RULES_FAILURE: 'FETCH_BOOKING_RULES_FAILURE',
    
    UPDATE_STUDIO_FILTERS: 'UPDATE_STUDIO_FILTERS'
};